# Application Configuration
spring.application.name=finance_tracker
spring.config.import=optional:file:.env[.properties]

# Server Configuration
server.port=4047

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=finance_track
spring.data.mongodb.auto-index-creation=true

#Debugging Configuration
debug=false
logging.level.org.springframework.data.mongodb=DEBUG

